### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by Telous** [artgris/PageBundle#1]
Hi, I just made a clean installation of symfony 4, then EasyAdminBundle and finally PageBundle.
When executing the command: `php bin/console doctrine: schema: update --force`, I get the following error: 

> No identifier / primary key specified for Entity "Artgris \ Bundle \ PageBundle \ Entity \ ArtgrisBlockTranslation". Every Entity must have an identifier / primary key.

Any idea what could it be?

**Comment by artgris** [comment]
Hi, sorry I forgot the doctrine behaviors configuration in my readme.

Add locale parameter in services.yaml:

```
  parameters:
      locale: 'en'
```

Add to AppKernel:

```
  <?php

  return [
      ...
      Knp\DoctrineBehaviors\Bundle\DoctrineBehaviorsBundle::class => ['all' => true],
  ];
```

**Comment by Telous** [comment]
I'm really sorry for not responding, but I've been really busy. I have configured as you have explained and it worked fine. Thanks a lot.
