### ISSUE TITLE
Add slug on array key with {{ page() }}

### ISSUE THREAD

**Issue by devcut** [artgris/PageBundle#8]
I want to use a block page in any page of my website but if i made a dump of `{{ dump(page('homepage')) }}` and i have an array with keys equal `0,1,2,3` and the value.

I have for example a field slug `facebook` with value but in my array I don't know which one it is because they are numbers.

I would use this twig function like this : `{{ page('homepage')['facebook'] }}` 

It's possible to make a pull request for change this in `BlockExtension` ? 

```php
  public function getPage(string $page)
  {
      $page = $this->pageService->getPageBySlug($page);
      $value = [];
      foreach ($page->getBlocks() as $block) {
          $value[$block->getSlug()] = $this->getBlockValue($block);
      }

      return $value;
  }
```

Thanks bro

**Comment by artgris** [comment]
`{{ blok('facebook') }}`
